version: '3'
services:
  bprl-optical-flow-container:
    image: bprl/optical-flow-ros:latest
    container_name: bprl-optical-flow-ros-container
    restart: always
    network_mode: host
    ipc: host
    privileged: true
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    command: -c ". install/setup.bash && ros2 launch optical_flow_bringup bringup.launch.py"
    volumes:
      #- ".:/workspaces/optical_flow"
      - "/dev/*:/dev/*"

