teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
      z: 7
    scale_linear:
      x: 1.5
      y: 1.5
      z: 0.5
    scale_linear_turbo:
      x: 3.0
      y: 3.0
      z: 1.0
    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 0.5
    enable_button: 5
    enable_turbo_button: 0
